// Mocks generated by Mockito 5.4.6 from annotations
// in uploader_app/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:connectivity_plus/connectivity_plus.dart' as _i13;
import 'package:flutter/foundation.dart' as _i14;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:shared_preferences/shared_preferences.dart' as _i12;
import 'package:uploader_app/models/models.dart' as _i2;
import 'package:uploader_app/services/auth_service.dart' as _i8;
import 'package:uploader_app/services/file_selection_service.dart' as _i11;
import 'package:uploader_app/services/http_client_service.dart' as _i5;
import 'package:uploader_app/services/upload_service.dart' as _i10;
import 'package:uploader_app/services/user_service.dart' as _i9;
import 'package:uploader_app/services/web_camera_service_stub.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T1> extends _i1.SmartFake
    implements _i2.ApiResponse<T1> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserStats_1 extends _i1.SmartFake implements _i2.UserStats {
  _FakeUserStats_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadStats_2 extends _i1.SmartFake implements _i2.UploadStats {
  _FakeUploadStats_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCameraCapture_3 extends _i1.SmartFake implements _i3.CameraCapture {
  _FakeCameraCapture_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileSelectionConfig_4 extends _i1.SmartFake
    implements _i2.FileSelectionConfig {
  _FakeFileSelectionConfig_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_5 extends _i1.SmartFake implements _i4.IOSOptions {
  _FakeIOSOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_6 extends _i1.SmartFake
    implements _i4.AndroidOptions {
  _FakeAndroidOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_7 extends _i1.SmartFake implements _i4.LinuxOptions {
  _FakeLinuxOptions_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_8 extends _i1.SmartFake
    implements _i4.WindowsOptions {
  _FakeWindowsOptions_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_9 extends _i1.SmartFake implements _i4.WebOptions {
  _FakeWebOptions_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_10 extends _i1.SmartFake implements _i4.MacOsOptions {
  _FakeMacOsOptions_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpClientService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClientService extends _i1.Mock implements _i5.HttpClientService {
  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setToken(_i2.AuthTokenModel? token) => super.noSuchMethod(
    Invocation.method(#setToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void setUser(_i2.Employee? user) => super.noSuchMethod(
    Invocation.method(#setUser, [user]),
    returnValueForMissingStub: null,
  );

  @override
  void clearAuth() => super.noSuchMethod(
    Invocation.method(#clearAuth, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i2.ApiResponse<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParams,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    bool? retryOnFailure = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #queryParams: queryParams,
                #headers: headers,
                #fromJson: fromJson,
                #retryOnFailure: retryOnFailure,
              },
            ),
            returnValue: _i7.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #queryParams: queryParams,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #queryParams: queryParams,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i2.ApiResponse<T>>);

  @override
  _i7.Future<_i2.ApiResponse<T>> post<T>(
    String? path, {
    dynamic body,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    bool? retryOnFailure = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #body: body,
                #headers: headers,
                #fromJson: fromJson,
                #retryOnFailure: retryOnFailure,
              },
            ),
            returnValue: _i7.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i2.ApiResponse<T>>);

  @override
  _i7.Future<_i2.ApiResponse<T>> put<T>(
    String? path, {
    dynamic body,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    bool? retryOnFailure = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #body: body,
                #headers: headers,
                #fromJson: fromJson,
                #retryOnFailure: retryOnFailure,
              },
            ),
            returnValue: _i7.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i2.ApiResponse<T>>);

  @override
  _i7.Future<_i2.ApiResponse<T>> delete<T>(
    String? path, {
    dynamic body,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    bool? retryOnFailure = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #body: body,
                #headers: headers,
                #fromJson: fromJson,
                #retryOnFailure: retryOnFailure,
              },
            ),
            returnValue: _i7.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i2.ApiResponse<T>>);

  @override
  _i7.Future<_i2.ApiResponse<T>> uploadFile<T>(
    String? path,
    String? fieldName,
    List<int>? fileBytes,
    String? fileName,
    String? mimeType, {
    Map<String, String>? fields,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    dynamic Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [path, fieldName, fileBytes, fileName, mimeType],
              {
                #fields: fields,
                #headers: headers,
                #fromJson: fromJson,
                #onProgress: onProgress,
              },
            ),
            returnValue: _i7.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #uploadFile,
                  [path, fieldName, fileBytes, fileName, mimeType],
                  {
                    #fields: fields,
                    #headers: headers,
                    #fromJson: fromJson,
                    #onProgress: onProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #uploadFile,
                  [path, fieldName, fileBytes, fileName, mimeType],
                  {
                    #fields: fields,
                    #headers: headers,
                    #fromJson: fromJson,
                    #onProgress: onProgress,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i2.ApiResponse<T>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i8.AuthService {
  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAdmin =>
      (super.noSuchMethod(
            Invocation.getter(#isAdmin),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isUploader =>
      (super.noSuchMethod(
            Invocation.getter(#isUploader),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.ApiResponse<_i2.AuthTokenModel>> register(
    String? username,
    String? email,
    String? password,
    String? firstName,
    String? lastName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [
              username,
              email,
              password,
              firstName,
              lastName,
            ]),
            returnValue: _i7.Future<_i2.ApiResponse<_i2.AuthTokenModel>>.value(
              _FakeApiResponse_0<_i2.AuthTokenModel>(
                this,
                Invocation.method(#register, [
                  username,
                  email,
                  password,
                  firstName,
                  lastName,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i2.ApiResponse<_i2.AuthTokenModel>>.value(
                  _FakeApiResponse_0<_i2.AuthTokenModel>(
                    this,
                    Invocation.method(#register, [
                      username,
                      email,
                      password,
                      firstName,
                      lastName,
                    ]),
                  ),
                ),
          )
          as _i7.Future<_i2.ApiResponse<_i2.AuthTokenModel>>);

  @override
  _i7.Future<_i2.ApiResponse<_i2.AuthTokenModel>> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i7.Future<_i2.ApiResponse<_i2.AuthTokenModel>>.value(
              _FakeApiResponse_0<_i2.AuthTokenModel>(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i2.ApiResponse<_i2.AuthTokenModel>>.value(
                  _FakeApiResponse_0<_i2.AuthTokenModel>(
                    this,
                    Invocation.method(#login, [username, password]),
                  ),
                ),
          )
          as _i7.Future<_i2.ApiResponse<_i2.AuthTokenModel>>);

  @override
  _i7.Future<_i2.ApiResponse<_i2.AuthTokenModel>> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i7.Future<_i2.ApiResponse<_i2.AuthTokenModel>>.value(
              _FakeApiResponse_0<_i2.AuthTokenModel>(
                this,
                Invocation.method(#refreshToken, []),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i2.ApiResponse<_i2.AuthTokenModel>>.value(
                  _FakeApiResponse_0<_i2.AuthTokenModel>(
                    this,
                    Invocation.method(#refreshToken, []),
                  ),
                ),
          )
          as _i7.Future<_i2.ApiResponse<_i2.AuthTokenModel>>);

  @override
  _i7.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> ensureValidToken() =>
      (super.noSuchMethod(
            Invocation.method(#ensureValidToken, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i2.ApiResponse<void>> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i7.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#changePassword, [], {
                  #currentPassword: currentPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#changePassword, [], {
                  #currentPassword: currentPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.ApiResponse<void>>);

  @override
  _i7.Future<_i2.ApiResponse<_i2.Employee>> updateProfile({
    String? firstName,
    String? lastName,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
            }),
            returnValue: _i7.Future<_i2.ApiResponse<_i2.Employee>>.value(
              _FakeApiResponse_0<_i2.Employee>(
                this,
                Invocation.method(#updateProfile, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i2.ApiResponse<_i2.Employee>>.value(
                  _FakeApiResponse_0<_i2.Employee>(
                    this,
                    Invocation.method(#updateProfile, [], {
                      #firstName: firstName,
                      #lastName: lastName,
                      #email: email,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i2.ApiResponse<_i2.Employee>>);

  @override
  bool hasPermission(String? permission) =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, [permission]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i9.UserService {
  @override
  _i7.Stream<List<_i2.UserModel>> get usersStream =>
      (super.noSuchMethod(
            Invocation.getter(#usersStream),
            returnValue: _i7.Stream<List<_i2.UserModel>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i2.UserModel>>.empty(),
          )
          as _i7.Stream<List<_i2.UserModel>>);

  @override
  _i7.Stream<bool> get loadingStream =>
      (super.noSuchMethod(
            Invocation.getter(#loadingStream),
            returnValue: _i7.Stream<bool>.empty(),
            returnValueForMissingStub: _i7.Stream<bool>.empty(),
          )
          as _i7.Stream<bool>);

  @override
  List<_i2.UserModel> get currentUsers =>
      (super.noSuchMethod(
            Invocation.getter(#currentUsers),
            returnValue: <_i2.UserModel>[],
            returnValueForMissingStub: <_i2.UserModel>[],
          )
          as List<_i2.UserModel>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isCacheValidForTesting =>
      (super.noSuchMethod(
            Invocation.getter(#isCacheValidForTesting),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i2.UserModel> get cachedUsersForTesting =>
      (super.noSuchMethod(
            Invocation.getter(#cachedUsersForTesting),
            returnValue: <_i2.UserModel>[],
            returnValueForMissingStub: <_i2.UserModel>[],
          )
          as List<_i2.UserModel>);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.ApiResponse<List<_i2.UserModel>>> fetchUsers({
    bool? forceRefresh = false,
    Map<String, dynamic>? filters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUsers, [], {
              #forceRefresh: forceRefresh,
              #filters: filters,
            }),
            returnValue: _i7.Future<_i2.ApiResponse<List<_i2.UserModel>>>.value(
              _FakeApiResponse_0<List<_i2.UserModel>>(
                this,
                Invocation.method(#fetchUsers, [], {
                  #forceRefresh: forceRefresh,
                  #filters: filters,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i2.ApiResponse<List<_i2.UserModel>>>.value(
                  _FakeApiResponse_0<List<_i2.UserModel>>(
                    this,
                    Invocation.method(#fetchUsers, [], {
                      #forceRefresh: forceRefresh,
                      #filters: filters,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i2.ApiResponse<List<_i2.UserModel>>>);

  @override
  _i7.Future<_i2.ApiResponse<List<_i2.UserModel>>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i7.Future<_i2.ApiResponse<List<_i2.UserModel>>>.value(
              _FakeApiResponse_0<List<_i2.UserModel>>(
                this,
                Invocation.method(#searchUsers, [query]),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i2.ApiResponse<List<_i2.UserModel>>>.value(
                  _FakeApiResponse_0<List<_i2.UserModel>>(
                    this,
                    Invocation.method(#searchUsers, [query]),
                  ),
                ),
          )
          as _i7.Future<_i2.ApiResponse<List<_i2.UserModel>>>);

  @override
  _i7.Future<_i2.ApiResponse<_i2.UserModel>> getUserById(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i7.Future<_i2.ApiResponse<_i2.UserModel>>.value(
              _FakeApiResponse_0<_i2.UserModel>(
                this,
                Invocation.method(#getUserById, [userId]),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i2.ApiResponse<_i2.UserModel>>.value(
                  _FakeApiResponse_0<_i2.UserModel>(
                    this,
                    Invocation.method(#getUserById, [userId]),
                  ),
                ),
          )
          as _i7.Future<_i2.ApiResponse<_i2.UserModel>>);

  @override
  List<_i2.UserModel> filterUsers({
    String? username,
    String? email,
    String? firstName,
    String? lastName,
    bool? isActive,
    DateTime? createdAfter,
    DateTime? createdBefore,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#filterUsers, [], {
              #username: username,
              #email: email,
              #firstName: firstName,
              #lastName: lastName,
              #isActive: isActive,
              #createdAfter: createdAfter,
              #createdBefore: createdBefore,
            }),
            returnValue: <_i2.UserModel>[],
            returnValueForMissingStub: <_i2.UserModel>[],
          )
          as List<_i2.UserModel>);

  @override
  List<_i2.UserModel> getUsersForSelection({String? searchQuery}) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersForSelection, [], {
              #searchQuery: searchQuery,
            }),
            returnValue: <_i2.UserModel>[],
            returnValueForMissingStub: <_i2.UserModel>[],
          )
          as List<_i2.UserModel>);

  @override
  _i7.Future<void> refreshUsers() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUsers, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i2.UserStats getUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#getUserStats, []),
            returnValue: _FakeUserStats_1(
              this,
              Invocation.method(#getUserStats, []),
            ),
            returnValueForMissingStub: _FakeUserStats_1(
              this,
              Invocation.method(#getUserStats, []),
            ),
          )
          as _i2.UserStats);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void setCachedUsersForTesting(List<_i2.UserModel>? users) =>
      super.noSuchMethod(
        Invocation.method(#setCachedUsersForTesting, [users]),
        returnValueForMissingStub: null,
      );

  @override
  void setLastFetchTimeForTesting(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastFetchTimeForTesting, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void addLoadingStateForTesting(bool? isLoading) => super.noSuchMethod(
    Invocation.method(#addLoadingStateForTesting, [isLoading]),
    returnValueForMissingStub: null,
  );

  @override
  void addUsersUpdateForTesting(List<_i2.UserModel>? users) =>
      super.noSuchMethod(
        Invocation.method(#addUsersUpdateForTesting, [users]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UploadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadService extends _i1.Mock implements _i10.UploadService {
  @override
  _i7.Stream<_i2.Upload> get uploadStream =>
      (super.noSuchMethod(
            Invocation.getter(#uploadStream),
            returnValue: _i7.Stream<_i2.Upload>.empty(),
            returnValueForMissingStub: _i7.Stream<_i2.Upload>.empty(),
          )
          as _i7.Stream<_i2.Upload>);

  @override
  _i7.Stream<double> get progressStream =>
      (super.noSuchMethod(
            Invocation.getter(#progressStream),
            returnValue: _i7.Stream<double>.empty(),
            returnValueForMissingStub: _i7.Stream<double>.empty(),
          )
          as _i7.Stream<double>);

  @override
  List<_i2.UploadQueueItem> get uploadQueue =>
      (super.noSuchMethod(
            Invocation.getter(#uploadQueue),
            returnValue: <_i2.UploadQueueItem>[],
            returnValueForMissingStub: <_i2.UploadQueueItem>[],
          )
          as List<_i2.UploadQueueItem>);

  @override
  int get activeUploads =>
      (super.noSuchMethod(
            Invocation.getter(#activeUploads),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get queuedUploads =>
      (super.noSuchMethod(
            Invocation.getter(#queuedUploads),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i7.Future<_i2.ApiResponse<_i2.Upload>> uploadFile({
    required String? fileName,
    required List<int>? fileBytes,
    required String? mimeType,
    int? userId,
    Map<String, String>? additionalFields,
    dynamic Function(double)? onProgress,
    dynamic Function(_i2.Upload)? onComplete,
    dynamic Function(String)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [], {
              #fileName: fileName,
              #fileBytes: fileBytes,
              #mimeType: mimeType,
              #userId: userId,
              #additionalFields: additionalFields,
              #onProgress: onProgress,
              #onComplete: onComplete,
              #onError: onError,
            }),
            returnValue: _i7.Future<_i2.ApiResponse<_i2.Upload>>.value(
              _FakeApiResponse_0<_i2.Upload>(
                this,
                Invocation.method(#uploadFile, [], {
                  #fileName: fileName,
                  #fileBytes: fileBytes,
                  #mimeType: mimeType,
                  #userId: userId,
                  #additionalFields: additionalFields,
                  #onProgress: onProgress,
                  #onComplete: onComplete,
                  #onError: onError,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i2.ApiResponse<_i2.Upload>>.value(
                  _FakeApiResponse_0<_i2.Upload>(
                    this,
                    Invocation.method(#uploadFile, [], {
                      #fileName: fileName,
                      #fileBytes: fileBytes,
                      #mimeType: mimeType,
                      #userId: userId,
                      #additionalFields: additionalFields,
                      #onProgress: onProgress,
                      #onComplete: onComplete,
                      #onError: onError,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i2.ApiResponse<_i2.Upload>>);

  @override
  _i7.Future<_i2.ApiResponse<_i2.Upload>> uploadFileFromPath({
    required String? filePath,
    required String? fileName,
    required int? fileSize,
    required String? mimeType,
    int? userId,
    Map<String, String>? additionalFields,
    dynamic Function(double)? onProgress,
    dynamic Function(_i2.Upload)? onComplete,
    dynamic Function(String)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFileFromPath, [], {
              #filePath: filePath,
              #fileName: fileName,
              #fileSize: fileSize,
              #mimeType: mimeType,
              #userId: userId,
              #additionalFields: additionalFields,
              #onProgress: onProgress,
              #onComplete: onComplete,
              #onError: onError,
            }),
            returnValue: _i7.Future<_i2.ApiResponse<_i2.Upload>>.value(
              _FakeApiResponse_0<_i2.Upload>(
                this,
                Invocation.method(#uploadFileFromPath, [], {
                  #filePath: filePath,
                  #fileName: fileName,
                  #fileSize: fileSize,
                  #mimeType: mimeType,
                  #userId: userId,
                  #additionalFields: additionalFields,
                  #onProgress: onProgress,
                  #onComplete: onComplete,
                  #onError: onError,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i2.ApiResponse<_i2.Upload>>.value(
                  _FakeApiResponse_0<_i2.Upload>(
                    this,
                    Invocation.method(#uploadFileFromPath, [], {
                      #filePath: filePath,
                      #fileName: fileName,
                      #fileSize: fileSize,
                      #mimeType: mimeType,
                      #userId: userId,
                      #additionalFields: additionalFields,
                      #onProgress: onProgress,
                      #onComplete: onComplete,
                      #onError: onError,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i2.ApiResponse<_i2.Upload>>);

  @override
  _i7.Future<bool> cancelUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelUpload, [uploadId]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void cancelAllUploads() => super.noSuchMethod(
    Invocation.method(#cancelAllUploads, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> retryUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#retryUpload, [uploadId]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i2.UploadStats getUploadStats() =>
      (super.noSuchMethod(
            Invocation.method(#getUploadStats, []),
            returnValue: _FakeUploadStats_2(
              this,
              Invocation.method(#getUploadStats, []),
            ),
            returnValueForMissingStub: _FakeUploadStats_2(
              this,
              Invocation.method(#getUploadStats, []),
            ),
          )
          as _i2.UploadStats);

  @override
  void clearCompletedUploads() => super.noSuchMethod(
    Invocation.method(#clearCompletedUploads, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WebCameraService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebCameraService extends _i1.Mock implements _i3.WebCameraService {
  @override
  _i7.Stream<_i3.CameraDevice?> get deviceStream =>
      (super.noSuchMethod(
            Invocation.getter(#deviceStream),
            returnValue: _i7.Stream<_i3.CameraDevice?>.empty(),
            returnValueForMissingStub: _i7.Stream<_i3.CameraDevice?>.empty(),
          )
          as _i7.Stream<_i3.CameraDevice?>);

  @override
  _i7.Stream<bool> get streamingStream =>
      (super.noSuchMethod(
            Invocation.getter(#streamingStream),
            returnValue: _i7.Stream<bool>.empty(),
            returnValueForMissingStub: _i7.Stream<bool>.empty(),
          )
          as _i7.Stream<bool>);

  @override
  bool get isStreaming =>
      (super.noSuchMethod(
            Invocation.getter(#isStreaming),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.CameraDevice>> getAvailableCameras() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableCameras, []),
            returnValue: _i7.Future<List<_i3.CameraDevice>>.value(
              <_i3.CameraDevice>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i3.CameraDevice>>.value(
              <_i3.CameraDevice>[],
            ),
          )
          as _i7.Future<List<_i3.CameraDevice>>);

  @override
  _i7.Future<void> startStream([_i3.CameraDevice? device]) =>
      (super.noSuchMethod(
            Invocation.method(#startStream, [device]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> stopStream() =>
      (super.noSuchMethod(
            Invocation.method(#stopStream, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.CameraCapture> capturePhoto({
    double? quality = 0.8,
    int? maxWidth,
    int? maxHeight,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#capturePhoto, [], {
              #quality: quality,
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
            }),
            returnValue: _i7.Future<_i3.CameraCapture>.value(
              _FakeCameraCapture_3(
                this,
                Invocation.method(#capturePhoto, [], {
                  #quality: quality,
                  #maxWidth: maxWidth,
                  #maxHeight: maxHeight,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.CameraCapture>.value(
              _FakeCameraCapture_3(
                this,
                Invocation.method(#capturePhoto, [], {
                  #quality: quality,
                  #maxWidth: maxWidth,
                  #maxHeight: maxHeight,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.CameraCapture>);

  @override
  String getPreviewElementId() =>
      (super.noSuchMethod(
            Invocation.method(#getPreviewElementId, []),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getPreviewElementId, []),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.method(#getPreviewElementId, []),
            ),
          )
          as String);

  @override
  _i7.Future<bool> checkPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermissions, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [FileSelectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileSelectionService extends _i1.Mock
    implements _i11.FileSelectionService {
  @override
  _i7.Stream<List<_i2.SelectedFile>> get filesStream =>
      (super.noSuchMethod(
            Invocation.getter(#filesStream),
            returnValue: _i7.Stream<List<_i2.SelectedFile>>.empty(),
            returnValueForMissingStub:
                _i7.Stream<List<_i2.SelectedFile>>.empty(),
          )
          as _i7.Stream<List<_i2.SelectedFile>>);

  @override
  _i7.Stream<double> get progressStream =>
      (super.noSuchMethod(
            Invocation.getter(#progressStream),
            returnValue: _i7.Stream<double>.empty(),
            returnValueForMissingStub: _i7.Stream<double>.empty(),
          )
          as _i7.Stream<double>);

  @override
  List<_i2.SelectedFile> get selectedFiles =>
      (super.noSuchMethod(
            Invocation.getter(#selectedFiles),
            returnValue: <_i2.SelectedFile>[],
            returnValueForMissingStub: <_i2.SelectedFile>[],
          )
          as List<_i2.SelectedFile>);

  @override
  _i2.FileSelectionConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeFileSelectionConfig_4(
              this,
              Invocation.getter(#config),
            ),
            returnValueForMissingStub: _FakeFileSelectionConfig_4(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i2.FileSelectionConfig);

  @override
  int get totalSize =>
      (super.noSuchMethod(
            Invocation.getter(#totalSize),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String get formattedTotalSize =>
      (super.noSuchMethod(
            Invocation.getter(#formattedTotalSize),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#formattedTotalSize),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#formattedTotalSize),
            ),
          )
          as String);

  @override
  void updateConfig(_i2.FileSelectionConfig? newConfig) => super.noSuchMethod(
    Invocation.method(#updateConfig, [newConfig]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<List<_i2.SelectedFile>> pickFiles({
    _i2.FileSelectionConfig? config,
    bool? fromGallery = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickFiles, [], {
              #config: config,
              #fromGallery: fromGallery,
            }),
            returnValue: _i7.Future<List<_i2.SelectedFile>>.value(
              <_i2.SelectedFile>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i2.SelectedFile>>.value(
              <_i2.SelectedFile>[],
            ),
          )
          as _i7.Future<List<_i2.SelectedFile>>);

  @override
  void clearFiles() => super.noSuchMethod(
    Invocation.method(#clearFiles, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeFile(_i2.SelectedFile? file) => super.noSuchMethod(
    Invocation.method(#removeFile, [file]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i12.SharedPreferences {
  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValueForMissingStub: null,
          )
          as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValueForMissingStub: null,
          )
          as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key]),
            returnValueForMissingStub: null,
          )
          as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValueForMissingStub: null,
          )
          as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getStringList, [key]),
            returnValueForMissingStub: null,
          )
          as List<String>?);

  @override
  _i7.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i13.Connectivity {
  @override
  _i7.Stream<List<_i13.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i7.Stream<List<_i13.ConnectivityResult>>.empty(),
            returnValueForMissingStub:
                _i7.Stream<List<_i13.ConnectivityResult>>.empty(),
          )
          as _i7.Stream<List<_i13.ConnectivityResult>>);

  @override
  _i7.Future<List<_i13.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i7.Future<List<_i13.ConnectivityResult>>.value(
              <_i13.ConnectivityResult>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i13.ConnectivityResult>>.value(
                  <_i13.ConnectivityResult>[],
                ),
          )
          as _i7.Future<List<_i13.ConnectivityResult>>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i4.FlutterSecureStorage {
  @override
  _i4.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_5(this, Invocation.getter(#iOptions)),
            returnValueForMissingStub: _FakeIOSOptions_5(
              this,
              Invocation.getter(#iOptions),
            ),
          )
          as _i4.IOSOptions);

  @override
  _i4.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_6(
              this,
              Invocation.getter(#aOptions),
            ),
            returnValueForMissingStub: _FakeAndroidOptions_6(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i4.AndroidOptions);

  @override
  _i4.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_7(
              this,
              Invocation.getter(#lOptions),
            ),
            returnValueForMissingStub: _FakeLinuxOptions_7(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i4.LinuxOptions);

  @override
  _i4.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_8(
              this,
              Invocation.getter(#wOptions),
            ),
            returnValueForMissingStub: _FakeWindowsOptions_8(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i4.WindowsOptions);

  @override
  _i4.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_9(
              this,
              Invocation.getter(#webOptions),
            ),
            returnValueForMissingStub: _FakeWebOptions_9(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i4.WebOptions);

  @override
  _i4.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_10(
              this,
              Invocation.getter(#mOptions),
            ),
            returnValueForMissingStub: _FakeMacOsOptions_10(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i4.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i14.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i14.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> write({
    required String? key,
    required String? value,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> read({
    required String? key,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<bool> containsKey({
    required String? key,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> delete({
    required String? key,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, String>> readAll({
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i7.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i7.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i7.Future<Map<String, String>>);

  @override
  _i7.Future<void> deleteAll({
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i7.Future<bool?>.value(),
            returnValueForMissingStub: _i7.Future<bool?>.value(),
          )
          as _i7.Future<bool?>);
}
