// Mocks for testing
// This file will be auto-generated by build_runner
// Run: flutter pub run build_runner build

import 'package:mockito/annotations.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

import 'package:uploader_app/services/services.dart';

@GenerateNiceMocks([
  MockSpec<HttpClientService>(),
  MockSpec<AuthService>(),
  MockSpec<UserService>(),
  MockSpec<UploadService>(),
  MockSpec<WebCameraService>(),
  MockSpec<FileSelectionService>(),
  MockSpec<SharedPreferences>(),
  MockSpec<Connectivity>(),
  MockSpec<FlutterSecureStorage>(),
])
void main() {}
