// Mocks generated by Mockito 5.4.6 from annotations
// in uploader_app/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:connectivity_plus/connectivity_plus.dart' as _i13;
import 'package:flutter/foundation.dart' as _i14;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:shared_preferences/shared_preferences.dart' as _i12;
import 'package:uploader_app/models/models.dart' as _i2;
import 'package:uploader_app/services/auth_service.dart' as _i11;
import 'package:uploader_app/services/file_selection_service.dart' as _i6;
import 'package:uploader_app/services/http_client_service.dart' as _i8;
import 'package:uploader_app/services/upload_service.dart' as _i4;
import 'package:uploader_app/services/user_service.dart' as _i3;
import 'package:uploader_app/services/web_camera_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T1> extends _i1.SmartFake
    implements _i2.ApiResponse<T1> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserStats_1 extends _i1.SmartFake implements _i3.UserStats {
  _FakeUserStats_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpload_2 extends _i1.SmartFake implements _i2.Upload {
  _FakeUpload_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadStats_3 extends _i1.SmartFake implements _i4.UploadStats {
  _FakeUploadStats_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCameraCapture_4 extends _i1.SmartFake implements _i5.CameraCapture {
  _FakeCameraCapture_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileSelectionConfig_5 extends _i1.SmartFake
    implements _i6.FileSelectionConfig {
  _FakeFileSelectionConfig_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_6 extends _i1.SmartFake implements _i7.IOSOptions {
  _FakeIOSOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_7 extends _i1.SmartFake
    implements _i7.AndroidOptions {
  _FakeAndroidOptions_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_8 extends _i1.SmartFake implements _i7.LinuxOptions {
  _FakeLinuxOptions_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_9 extends _i1.SmartFake
    implements _i7.WindowsOptions {
  _FakeWindowsOptions_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_10 extends _i1.SmartFake implements _i7.WebOptions {
  _FakeWebOptions_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_11 extends _i1.SmartFake implements _i7.MacOsOptions {
  _FakeMacOsOptions_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpClientService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClientService extends _i1.Mock implements _i8.HttpClientService {
  MockHttpClientService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  void setToken(_i2.AuthTokenModel? token) => super.noSuchMethod(
    Invocation.method(#setToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void setUser(_i2.Employee? user) => super.noSuchMethod(
    Invocation.method(#setUser, [user]),
    returnValueForMissingStub: null,
  );

  @override
  void clearAuth() => super.noSuchMethod(
    Invocation.method(#clearAuth, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i2.ApiResponse<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParams,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    bool? retryOnFailure = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #queryParams: queryParams,
                #headers: headers,
                #fromJson: fromJson,
                #retryOnFailure: retryOnFailure,
              },
            ),
            returnValue: _i10.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #queryParams: queryParams,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i2.ApiResponse<T>>);

  @override
  _i10.Future<_i2.ApiResponse<T>> post<T>(
    String? path, {
    dynamic body,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    bool? retryOnFailure = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #body: body,
                #headers: headers,
                #fromJson: fromJson,
                #retryOnFailure: retryOnFailure,
              },
            ),
            returnValue: _i10.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i2.ApiResponse<T>>);

  @override
  _i10.Future<_i2.ApiResponse<T>> put<T>(
    String? path, {
    dynamic body,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    bool? retryOnFailure = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #body: body,
                #headers: headers,
                #fromJson: fromJson,
                #retryOnFailure: retryOnFailure,
              },
            ),
            returnValue: _i10.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i2.ApiResponse<T>>);

  @override
  _i10.Future<_i2.ApiResponse<T>> delete<T>(
    String? path, {
    dynamic body,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    bool? retryOnFailure = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #body: body,
                #headers: headers,
                #fromJson: fromJson,
                #retryOnFailure: retryOnFailure,
              },
            ),
            returnValue: _i10.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i2.ApiResponse<T>>);

  @override
  _i10.Future<_i2.ApiResponse<T>> uploadFile<T>(
    String? path,
    String? fieldName,
    List<int>? fileBytes,
    String? fileName,
    String? mimeType, {
    Map<String, String>? fields,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    dynamic Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [path, fieldName, fileBytes, fileName, mimeType],
              {
                #fields: fields,
                #headers: headers,
                #fromJson: fromJson,
                #onProgress: onProgress,
              },
            ),
            returnValue: _i10.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #uploadFile,
                  [path, fieldName, fileBytes, fileName, mimeType],
                  {
                    #fields: fields,
                    #headers: headers,
                    #fromJson: fromJson,
                    #onProgress: onProgress,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i2.ApiResponse<T>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i11.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isAdmin =>
      (super.noSuchMethod(Invocation.getter(#isAdmin), returnValue: false)
          as bool);

  @override
  bool get isUploader =>
      (super.noSuchMethod(Invocation.getter(#isUploader), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i10.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i2.ApiResponse<_i2.AuthTokenModel>> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i10.Future<_i2.ApiResponse<_i2.AuthTokenModel>>.value(
              _FakeApiResponse_0<_i2.AuthTokenModel>(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i10.Future<_i2.ApiResponse<_i2.AuthTokenModel>>);

  @override
  _i10.Future<_i2.ApiResponse<_i2.AuthTokenModel>> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i10.Future<_i2.ApiResponse<_i2.AuthTokenModel>>.value(
              _FakeApiResponse_0<_i2.AuthTokenModel>(
                this,
                Invocation.method(#refreshToken, []),
              ),
            ),
          )
          as _i10.Future<_i2.ApiResponse<_i2.AuthTokenModel>>);

  @override
  _i10.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> ensureValidToken() =>
      (super.noSuchMethod(
            Invocation.method(#ensureValidToken, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<_i2.ApiResponse<void>> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i10.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#changePassword, [], {
                  #currentPassword: currentPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i10.Future<_i2.ApiResponse<void>>);

  @override
  _i10.Future<_i2.ApiResponse<_i2.Employee>> updateProfile({
    String? firstName,
    String? lastName,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
            }),
            returnValue: _i10.Future<_i2.ApiResponse<_i2.Employee>>.value(
              _FakeApiResponse_0<_i2.Employee>(
                this,
                Invocation.method(#updateProfile, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                }),
              ),
            ),
          )
          as _i10.Future<_i2.ApiResponse<_i2.Employee>>);

  @override
  bool hasPermission(String? permission) =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, [permission]),
            returnValue: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i3.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<List<_i2.User>> get usersStream =>
      (super.noSuchMethod(
            Invocation.getter(#usersStream),
            returnValue: _i10.Stream<List<_i2.User>>.empty(),
          )
          as _i10.Stream<List<_i2.User>>);

  @override
  _i10.Stream<bool> get loadingStream =>
      (super.noSuchMethod(
            Invocation.getter(#loadingStream),
            returnValue: _i10.Stream<bool>.empty(),
          )
          as _i10.Stream<bool>);

  @override
  List<_i2.User> get currentUsers =>
      (super.noSuchMethod(
            Invocation.getter(#currentUsers),
            returnValue: <_i2.User>[],
          )
          as List<_i2.User>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  _i10.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i2.ApiResponse<List<_i2.User>>> fetchUsers({
    bool? forceRefresh = false,
    Map<String, dynamic>? filters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUsers, [], {
              #forceRefresh: forceRefresh,
              #filters: filters,
            }),
            returnValue: _i10.Future<_i2.ApiResponse<List<_i2.User>>>.value(
              _FakeApiResponse_0<List<_i2.User>>(
                this,
                Invocation.method(#fetchUsers, [], {
                  #forceRefresh: forceRefresh,
                  #filters: filters,
                }),
              ),
            ),
          )
          as _i10.Future<_i2.ApiResponse<List<_i2.User>>>);

  @override
  _i10.Future<_i2.ApiResponse<List<_i2.User>>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i10.Future<_i2.ApiResponse<List<_i2.User>>>.value(
              _FakeApiResponse_0<List<_i2.User>>(
                this,
                Invocation.method(#searchUsers, [query]),
              ),
            ),
          )
          as _i10.Future<_i2.ApiResponse<List<_i2.User>>>);

  @override
  _i10.Future<_i2.ApiResponse<_i2.User>> getUserById(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i10.Future<_i2.ApiResponse<_i2.User>>.value(
              _FakeApiResponse_0<_i2.User>(
                this,
                Invocation.method(#getUserById, [userId]),
              ),
            ),
          )
          as _i10.Future<_i2.ApiResponse<_i2.User>>);

  @override
  List<_i2.User> filterUsers({
    String? username,
    String? email,
    String? firstName,
    String? lastName,
    bool? isActive,
    DateTime? createdAfter,
    DateTime? createdBefore,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#filterUsers, [], {
              #username: username,
              #email: email,
              #firstName: firstName,
              #lastName: lastName,
              #isActive: isActive,
              #createdAfter: createdAfter,
              #createdBefore: createdBefore,
            }),
            returnValue: <_i2.User>[],
          )
          as List<_i2.User>);

  @override
  List<_i2.User> getUsersForSelection({String? searchQuery}) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersForSelection, [], {
              #searchQuery: searchQuery,
            }),
            returnValue: <_i2.User>[],
          )
          as List<_i2.User>);

  @override
  _i10.Future<void> refreshUsers() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUsers, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i3.UserStats getUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#getUserStats, []),
            returnValue: _FakeUserStats_1(
              this,
              Invocation.method(#getUserStats, []),
            ),
          )
          as _i3.UserStats);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UploadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadService extends _i1.Mock implements _i4.UploadService {
  MockUploadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<_i2.Upload> get uploadStream =>
      (super.noSuchMethod(
            Invocation.getter(#uploadStream),
            returnValue: _i10.Stream<_i2.Upload>.empty(),
          )
          as _i10.Stream<_i2.Upload>);

  @override
  _i10.Stream<double> get progressStream =>
      (super.noSuchMethod(
            Invocation.getter(#progressStream),
            returnValue: _i10.Stream<double>.empty(),
          )
          as _i10.Stream<double>);

  @override
  List<_i4.UploadQueueItem> get uploadQueue =>
      (super.noSuchMethod(
            Invocation.getter(#uploadQueue),
            returnValue: <_i4.UploadQueueItem>[],
          )
          as List<_i4.UploadQueueItem>);

  @override
  int get activeUploads =>
      (super.noSuchMethod(Invocation.getter(#activeUploads), returnValue: 0)
          as int);

  @override
  int get queuedUploads =>
      (super.noSuchMethod(Invocation.getter(#queuedUploads), returnValue: 0)
          as int);

  @override
  _i10.Future<_i2.Upload> uploadFile({
    required String? fileName,
    required List<int>? fileBytes,
    required String? mimeType,
    int? userId,
    Map<String, String>? additionalFields,
    dynamic Function(double)? onProgress,
    dynamic Function(_i2.Upload)? onComplete,
    dynamic Function(String)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [], {
              #fileName: fileName,
              #fileBytes: fileBytes,
              #mimeType: mimeType,
              #userId: userId,
              #additionalFields: additionalFields,
              #onProgress: onProgress,
              #onComplete: onComplete,
              #onError: onError,
            }),
            returnValue: _i10.Future<_i2.Upload>.value(
              _FakeUpload_2(
                this,
                Invocation.method(#uploadFile, [], {
                  #fileName: fileName,
                  #fileBytes: fileBytes,
                  #mimeType: mimeType,
                  #userId: userId,
                  #additionalFields: additionalFields,
                  #onProgress: onProgress,
                  #onComplete: onComplete,
                  #onError: onError,
                }),
              ),
            ),
          )
          as _i10.Future<_i2.Upload>);

  @override
  _i10.Future<_i2.Upload> uploadFileFromPath({
    required String? filePath,
    required String? fileName,
    required int? fileSize,
    required String? mimeType,
    int? userId,
    Map<String, String>? additionalFields,
    dynamic Function(double)? onProgress,
    dynamic Function(_i2.Upload)? onComplete,
    dynamic Function(String)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFileFromPath, [], {
              #filePath: filePath,
              #fileName: fileName,
              #fileSize: fileSize,
              #mimeType: mimeType,
              #userId: userId,
              #additionalFields: additionalFields,
              #onProgress: onProgress,
              #onComplete: onComplete,
              #onError: onError,
            }),
            returnValue: _i10.Future<_i2.Upload>.value(
              _FakeUpload_2(
                this,
                Invocation.method(#uploadFileFromPath, [], {
                  #filePath: filePath,
                  #fileName: fileName,
                  #fileSize: fileSize,
                  #mimeType: mimeType,
                  #userId: userId,
                  #additionalFields: additionalFields,
                  #onProgress: onProgress,
                  #onComplete: onComplete,
                  #onError: onError,
                }),
              ),
            ),
          )
          as _i10.Future<_i2.Upload>);

  @override
  _i10.Future<bool> cancelUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelUpload, [uploadId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  void cancelAllUploads() => super.noSuchMethod(
    Invocation.method(#cancelAllUploads, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<bool> retryUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#retryUpload, [uploadId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i4.UploadStats getUploadStats() =>
      (super.noSuchMethod(
            Invocation.method(#getUploadStats, []),
            returnValue: _FakeUploadStats_3(
              this,
              Invocation.method(#getUploadStats, []),
            ),
          )
          as _i4.UploadStats);

  @override
  void clearCompletedUploads() => super.noSuchMethod(
    Invocation.method(#clearCompletedUploads, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WebCameraService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebCameraService extends _i1.Mock implements _i5.WebCameraService {
  MockWebCameraService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<_i5.CameraDevice?> get deviceStream =>
      (super.noSuchMethod(
            Invocation.getter(#deviceStream),
            returnValue: _i10.Stream<_i5.CameraDevice?>.empty(),
          )
          as _i10.Stream<_i5.CameraDevice?>);

  @override
  _i10.Stream<bool> get streamingStream =>
      (super.noSuchMethod(
            Invocation.getter(#streamingStream),
            returnValue: _i10.Stream<bool>.empty(),
          )
          as _i10.Stream<bool>);

  @override
  bool get isStreaming =>
      (super.noSuchMethod(Invocation.getter(#isStreaming), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i10.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i5.CameraDevice>> getAvailableCameras() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableCameras, []),
            returnValue: _i10.Future<List<_i5.CameraDevice>>.value(
              <_i5.CameraDevice>[],
            ),
          )
          as _i10.Future<List<_i5.CameraDevice>>);

  @override
  _i10.Future<void> startStream([_i5.CameraDevice? device]) =>
      (super.noSuchMethod(
            Invocation.method(#startStream, [device]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> stopStream() =>
      (super.noSuchMethod(
            Invocation.method(#stopStream, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i5.CameraCapture> capturePhoto({
    double? quality = 0.8,
    int? maxWidth,
    int? maxHeight,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#capturePhoto, [], {
              #quality: quality,
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
            }),
            returnValue: _i10.Future<_i5.CameraCapture>.value(
              _FakeCameraCapture_4(
                this,
                Invocation.method(#capturePhoto, [], {
                  #quality: quality,
                  #maxWidth: maxWidth,
                  #maxHeight: maxHeight,
                }),
              ),
            ),
          )
          as _i10.Future<_i5.CameraCapture>);

  @override
  String getPreviewElementId() =>
      (super.noSuchMethod(
            Invocation.method(#getPreviewElementId, []),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getPreviewElementId, []),
            ),
          )
          as String);

  @override
  _i10.Future<bool> checkPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermissions, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [FileSelectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileSelectionService extends _i1.Mock
    implements _i6.FileSelectionService {
  MockFileSelectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<List<_i6.SelectedFile>> get filesStream =>
      (super.noSuchMethod(
            Invocation.getter(#filesStream),
            returnValue: _i10.Stream<List<_i6.SelectedFile>>.empty(),
          )
          as _i10.Stream<List<_i6.SelectedFile>>);

  @override
  _i10.Stream<double> get progressStream =>
      (super.noSuchMethod(
            Invocation.getter(#progressStream),
            returnValue: _i10.Stream<double>.empty(),
          )
          as _i10.Stream<double>);

  @override
  List<_i6.SelectedFile> get selectedFiles =>
      (super.noSuchMethod(
            Invocation.getter(#selectedFiles),
            returnValue: <_i6.SelectedFile>[],
          )
          as List<_i6.SelectedFile>);

  @override
  _i6.FileSelectionConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeFileSelectionConfig_5(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i6.FileSelectionConfig);

  @override
  int get totalSize =>
      (super.noSuchMethod(Invocation.getter(#totalSize), returnValue: 0)
          as int);

  @override
  String get formattedTotalSize =>
      (super.noSuchMethod(
            Invocation.getter(#formattedTotalSize),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#formattedTotalSize),
            ),
          )
          as String);

  @override
  void updateConfig(_i6.FileSelectionConfig? newConfig) => super.noSuchMethod(
    Invocation.method(#updateConfig, [newConfig]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<List<_i6.SelectedFile>> pickFiles({
    _i6.FileSelectionConfig? config,
    bool? fromGallery = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickFiles, [], {
              #config: config,
              #fromGallery: fromGallery,
            }),
            returnValue: _i10.Future<List<_i6.SelectedFile>>.value(
              <_i6.SelectedFile>[],
            ),
          )
          as _i10.Future<List<_i6.SelectedFile>>);

  @override
  void clearFiles() => super.noSuchMethod(
    Invocation.method(#clearFiles, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeFile(_i6.SelectedFile? file) => super.noSuchMethod(
    Invocation.method(#removeFile, [file]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i12.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i10.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i13.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<List<_i13.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i10.Stream<List<_i13.ConnectivityResult>>.empty(),
          )
          as _i10.Stream<List<_i13.ConnectivityResult>>);

  @override
  _i10.Future<List<_i13.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i10.Future<List<_i13.ConnectivityResult>>.value(
              <_i13.ConnectivityResult>[],
            ),
          )
          as _i10.Future<List<_i13.ConnectivityResult>>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i7.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_6(this, Invocation.getter(#iOptions)),
          )
          as _i7.IOSOptions);

  @override
  _i7.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_7(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i7.AndroidOptions);

  @override
  _i7.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_8(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i7.LinuxOptions);

  @override
  _i7.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_9(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i7.WindowsOptions);

  @override
  _i7.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_10(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i7.WebOptions);

  @override
  _i7.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_11(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i7.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i14.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i14.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> write({
    required String? key,
    required String? value,
    _i7.IOSOptions? iOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
    _i7.WebOptions? webOptions,
    _i7.MacOsOptions? mOptions,
    _i7.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String?> read({
    required String? key,
    _i7.IOSOptions? iOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
    _i7.WebOptions? webOptions,
    _i7.MacOsOptions? mOptions,
    _i7.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<bool> containsKey({
    required String? key,
    _i7.IOSOptions? iOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
    _i7.WebOptions? webOptions,
    _i7.MacOsOptions? mOptions,
    _i7.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> delete({
    required String? key,
    _i7.IOSOptions? iOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
    _i7.WebOptions? webOptions,
    _i7.MacOsOptions? mOptions,
    _i7.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<Map<String, String>> readAll({
    _i7.IOSOptions? iOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
    _i7.WebOptions? webOptions,
    _i7.MacOsOptions? mOptions,
    _i7.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i10.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i10.Future<Map<String, String>>);

  @override
  _i10.Future<void> deleteAll({
    _i7.IOSOptions? iOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
    _i7.WebOptions? webOptions,
    _i7.MacOsOptions? mOptions,
    _i7.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i10.Future<bool?>.value(),
          )
          as _i10.Future<bool?>);
}
