// Mocks for testing
// This file will be auto-generated by build_runner
// Run: flutter pub run build_runner build

import 'package:mockito/annotations.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

import '../../lib/services/services.dart';

@GenerateMocks([
  HttpClientService,
  AuthService,
  UserService,
  UploadService,
  WebCameraService,
  FileSelectionService,
  SharedPreferences,
  Connectivity,
  FlutterSecureStorage,
])
void main() {}

// Import the generated mocks
// import 'mocks.mocks.dart';