// Mocks generated by Mockito 5.4.6 from annotations
// in uploader_app/test/services/upload_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:connectivity_plus/connectivity_plus.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:uploader_app/models/models.dart' as _i2;
import 'package:uploader_app/services/http_client_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T1> extends _i1.SmartFake
    implements _i2.ApiResponse<T1> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpClientService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClientService extends _i1.Mock implements _i3.HttpClientService {
  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setToken(_i2.AuthTokenModel? token) => super.noSuchMethod(
    Invocation.method(#setToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void setUser(_i2.Employee? user) => super.noSuchMethod(
    Invocation.method(#setUser, [user]),
    returnValueForMissingStub: null,
  );

  @override
  void clearAuth() => super.noSuchMethod(
    Invocation.method(#clearAuth, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.ApiResponse<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParams,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    bool? retryOnFailure = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #queryParams: queryParams,
                #headers: headers,
                #fromJson: fromJson,
                #retryOnFailure: retryOnFailure,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #queryParams: queryParams,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #queryParams: queryParams,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<T>>);

  @override
  _i5.Future<_i2.ApiResponse<T>> post<T>(
    String? path, {
    dynamic body,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    bool? retryOnFailure = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #body: body,
                #headers: headers,
                #fromJson: fromJson,
                #retryOnFailure: retryOnFailure,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<T>>);

  @override
  _i5.Future<_i2.ApiResponse<T>> put<T>(
    String? path, {
    dynamic body,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    bool? retryOnFailure = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #body: body,
                #headers: headers,
                #fromJson: fromJson,
                #retryOnFailure: retryOnFailure,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<T>>);

  @override
  _i5.Future<_i2.ApiResponse<T>> delete<T>(
    String? path, {
    dynamic body,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    bool? retryOnFailure = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #body: body,
                #headers: headers,
                #fromJson: fromJson,
                #retryOnFailure: retryOnFailure,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                    #retryOnFailure: retryOnFailure,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<T>>);

  @override
  _i5.Future<_i2.ApiResponse<T>> uploadFile<T>(
    String? path,
    String? fieldName,
    List<int>? fileBytes,
    String? fileName,
    String? mimeType, {
    Map<String, String>? fields,
    Map<String, String>? headers,
    T Function(Map<String, dynamic>)? fromJson,
    dynamic Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [path, fieldName, fileBytes, fileName, mimeType],
              {
                #fields: fields,
                #headers: headers,
                #fromJson: fromJson,
                #onProgress: onProgress,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #uploadFile,
                  [path, fieldName, fileBytes, fileName, mimeType],
                  {
                    #fields: fields,
                    #headers: headers,
                    #fromJson: fromJson,
                    #onProgress: onProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #uploadFile,
                  [path, fieldName, fileBytes, fileName, mimeType],
                  {
                    #fields: fields,
                    #headers: headers,
                    #fromJson: fromJson,
                    #onProgress: onProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<T>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i6.Connectivity {
  @override
  _i5.Stream<List<_i6.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i5.Stream<List<_i6.ConnectivityResult>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<List<_i6.ConnectivityResult>>.empty(),
          )
          as _i5.Stream<List<_i6.ConnectivityResult>>);

  @override
  _i5.Future<List<_i6.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i5.Future<List<_i6.ConnectivityResult>>.value(
              <_i6.ConnectivityResult>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i6.ConnectivityResult>>.value(
                  <_i6.ConnectivityResult>[],
                ),
          )
          as _i5.Future<List<_i6.ConnectivityResult>>);
}
