// Mocks generated by Mockito 5.4.6 from annotations
// in user_app/test/unit/video_player_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i9;

import 'package:chewie/src/chewie_player.dart' as _i4;
import 'package:chewie/src/chewie_progress_colors.dart' as _i13;
import 'package:chewie/src/models/option_item.dart' as _i14;
import 'package:chewie/src/models/options_translation.dart' as _i12;
import 'package:chewie/src/models/subtitle_model.dart' as _i11;
import 'package:flutter/material.dart' as _i3;
import 'package:flutter/services.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:video_player/src/closed_caption_file.dart' as _i8;
import 'package:video_player/video_player.dart' as _i2;
import 'package:video_player_platform_interface/video_player_platform_interface.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeVideoPlayerValue_0 extends _i1.SmartFake
    implements _i2.VideoPlayerValue {
  _FakeVideoPlayerValue_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVideoPlayerController_1 extends _i1.SmartFake
    implements _i2.VideoPlayerController {
  _FakeVideoPlayerController_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEdgeInsets_3 extends _i1.SmartFake implements _i3.EdgeInsets {
  _FakeEdgeInsets_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChewieController_4 extends _i1.SmartFake
    implements _i4.ChewieController {
  _FakeChewieController_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VideoPlayerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoPlayerController extends _i1.Mock
    implements _i2.VideoPlayerController {
  MockVideoPlayerController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get dataSource =>
      (super.noSuchMethod(
            Invocation.getter(#dataSource),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#dataSource),
            ),
          )
          as String);

  @override
  Map<String, String> get httpHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#httpHeaders),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i6.DataSourceType get dataSourceType =>
      (super.noSuchMethod(
            Invocation.getter(#dataSourceType),
            returnValue: _i6.DataSourceType.asset,
          )
          as _i6.DataSourceType);

  @override
  _i6.VideoViewType get viewType =>
      (super.noSuchMethod(
            Invocation.getter(#viewType),
            returnValue: _i6.VideoViewType.textureView,
          )
          as _i6.VideoViewType);

  @override
  int get playerId =>
      (super.noSuchMethod(Invocation.getter(#playerId), returnValue: 0) as int);

  @override
  _i7.Future<Duration?> get position =>
      (super.noSuchMethod(
            Invocation.getter(#position),
            returnValue: _i7.Future<Duration?>.value(),
          )
          as _i7.Future<Duration?>);

  @override
  _i2.VideoPlayerValue get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: _FakeVideoPlayerValue_0(
              this,
              Invocation.getter(#value),
            ),
          )
          as _i2.VideoPlayerValue);

  @override
  set value(_i2.VideoPlayerValue? newValue) => super.noSuchMethod(
    Invocation.setter(#value, newValue),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setLooping(bool? looping) =>
      (super.noSuchMethod(
            Invocation.method(#setLooping, [looping]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> seekTo(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seekTo, [position]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setPlaybackSpeed(double? speed) =>
      (super.noSuchMethod(
            Invocation.method(#setPlaybackSpeed, [speed]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void setCaptionOffset(Duration? offset) => super.noSuchMethod(
    Invocation.method(#setCaptionOffset, [offset]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> setClosedCaptionFile(
    _i7.Future<_i8.ClosedCaptionFile>? closedCaptionFile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setClosedCaptionFile, [closedCaptionFile]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ChewieController].
///
/// See the documentation for Mockito's code generation for more information.
class MockChewieController extends _i1.Mock implements _i4.ChewieController {
  MockChewieController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get showOptions =>
      (super.noSuchMethod(Invocation.getter(#showOptions), returnValue: false)
          as bool);

  @override
  bool get showSubtitles =>
      (super.noSuchMethod(Invocation.getter(#showSubtitles), returnValue: false)
          as bool);

  @override
  _i2.VideoPlayerController get videoPlayerController =>
      (super.noSuchMethod(
            Invocation.getter(#videoPlayerController),
            returnValue: _FakeVideoPlayerController_1(
              this,
              Invocation.getter(#videoPlayerController),
            ),
          )
          as _i2.VideoPlayerController);

  @override
  bool get autoInitialize =>
      (super.noSuchMethod(
            Invocation.getter(#autoInitialize),
            returnValue: false,
          )
          as bool);

  @override
  bool get autoPlay =>
      (super.noSuchMethod(Invocation.getter(#autoPlay), returnValue: false)
          as bool);

  @override
  bool get draggableProgressBar =>
      (super.noSuchMethod(
            Invocation.getter(#draggableProgressBar),
            returnValue: false,
          )
          as bool);

  @override
  bool get looping =>
      (super.noSuchMethod(Invocation.getter(#looping), returnValue: false)
          as bool);

  @override
  bool get showControlsOnInitialize =>
      (super.noSuchMethod(
            Invocation.getter(#showControlsOnInitialize),
            returnValue: false,
          )
          as bool);

  @override
  bool get showControls =>
      (super.noSuchMethod(Invocation.getter(#showControls), returnValue: false)
          as bool);

  @override
  bool get zoomAndPan =>
      (super.noSuchMethod(Invocation.getter(#zoomAndPan), returnValue: false)
          as bool);

  @override
  double get maxScale =>
      (super.noSuchMethod(Invocation.getter(#maxScale), returnValue: 0.0)
          as double);

  @override
  Duration get materialSeekButtonFadeDuration =>
      (super.noSuchMethod(
            Invocation.getter(#materialSeekButtonFadeDuration),
            returnValue: _FakeDuration_2(
              this,
              Invocation.getter(#materialSeekButtonFadeDuration),
            ),
          )
          as Duration);

  @override
  double get materialSeekButtonSize =>
      (super.noSuchMethod(
            Invocation.getter(#materialSeekButtonSize),
            returnValue: 0.0,
          )
          as double);

  @override
  bool get fullScreenByDefault =>
      (super.noSuchMethod(
            Invocation.getter(#fullScreenByDefault),
            returnValue: false,
          )
          as bool);

  @override
  bool get allowedScreenSleep =>
      (super.noSuchMethod(
            Invocation.getter(#allowedScreenSleep),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLive =>
      (super.noSuchMethod(Invocation.getter(#isLive), returnValue: false)
          as bool);

  @override
  bool get allowFullScreen =>
      (super.noSuchMethod(
            Invocation.getter(#allowFullScreen),
            returnValue: false,
          )
          as bool);

  @override
  bool get allowMuting =>
      (super.noSuchMethod(Invocation.getter(#allowMuting), returnValue: false)
          as bool);

  @override
  bool get allowPlaybackSpeedChanging =>
      (super.noSuchMethod(
            Invocation.getter(#allowPlaybackSpeedChanging),
            returnValue: false,
          )
          as bool);

  @override
  bool get useRootNavigator =>
      (super.noSuchMethod(
            Invocation.getter(#useRootNavigator),
            returnValue: false,
          )
          as bool);

  @override
  Duration get hideControlsTimer =>
      (super.noSuchMethod(
            Invocation.getter(#hideControlsTimer),
            returnValue: _FakeDuration_2(
              this,
              Invocation.getter(#hideControlsTimer),
            ),
          )
          as Duration);

  @override
  List<double> get playbackSpeeds =>
      (super.noSuchMethod(
            Invocation.getter(#playbackSpeeds),
            returnValue: <double>[],
          )
          as List<double>);

  @override
  List<_i10.SystemUiOverlay> get systemOverlaysAfterFullScreen =>
      (super.noSuchMethod(
            Invocation.getter(#systemOverlaysAfterFullScreen),
            returnValue: <_i10.SystemUiOverlay>[],
          )
          as List<_i10.SystemUiOverlay>);

  @override
  List<_i10.DeviceOrientation> get deviceOrientationsAfterFullScreen =>
      (super.noSuchMethod(
            Invocation.getter(#deviceOrientationsAfterFullScreen),
            returnValue: <_i10.DeviceOrientation>[],
          )
          as List<_i10.DeviceOrientation>);

  @override
  _i3.EdgeInsets get controlsSafeAreaMinimum =>
      (super.noSuchMethod(
            Invocation.getter(#controlsSafeAreaMinimum),
            returnValue: _FakeEdgeInsets_3(
              this,
              Invocation.getter(#controlsSafeAreaMinimum),
            ),
          )
          as _i3.EdgeInsets);

  @override
  bool get pauseOnBackgroundTap =>
      (super.noSuchMethod(
            Invocation.getter(#pauseOnBackgroundTap),
            returnValue: false,
          )
          as bool);

  @override
  bool get isFullScreen =>
      (super.noSuchMethod(Invocation.getter(#isFullScreen), returnValue: false)
          as bool);

  @override
  bool get isPlaying =>
      (super.noSuchMethod(Invocation.getter(#isPlaying), returnValue: false)
          as bool);

  @override
  set subtitleBuilder(_i3.Widget Function(_i3.BuildContext, dynamic)? value) =>
      super.noSuchMethod(
        Invocation.setter(#subtitleBuilder, value),
        returnValueForMissingStub: null,
      );

  @override
  set subtitle(_i11.Subtitles? value) => super.noSuchMethod(
    Invocation.setter(#subtitle, value),
    returnValueForMissingStub: null,
  );

  @override
  set showSubtitles(bool? value) => super.noSuchMethod(
    Invocation.setter(#showSubtitles, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.ChewieController copyWith({
    _i2.VideoPlayerController? videoPlayerController,
    _i12.OptionsTranslation? optionsTranslation,
    double? aspectRatio,
    bool? autoInitialize,
    bool? autoPlay,
    bool? draggableProgressBar,
    Duration? startAt,
    bool? looping,
    bool? fullScreenByDefault,
    _i13.ChewieProgressColors? cupertinoProgressColors,
    _i13.ChewieProgressColors? materialProgressColors,
    Duration? materialSeekButtonFadeDuration,
    double? materialSeekButtonSize,
    _i3.Widget? placeholder,
    _i3.Widget? overlay,
    bool? showControlsOnInitialize,
    bool? showOptions,
    _i7.Future<void> Function(_i3.BuildContext, List<_i14.OptionItem>)?
    optionsBuilder,
    List<_i14.OptionItem> Function(_i3.BuildContext)? additionalOptions,
    bool? showControls,
    _i3.TransformationController? transformationController,
    bool? zoomAndPan,
    double? maxScale,
    _i11.Subtitles? subtitle,
    bool? showSubtitles,
    _i3.Widget Function(_i3.BuildContext, dynamic)? subtitleBuilder,
    _i3.Widget? customControls,
    _i3.WidgetBuilder? bufferingBuilder,
    _i3.Widget Function(_i3.BuildContext, String)? errorBuilder,
    bool? allowedScreenSleep,
    bool? isLive,
    bool? allowFullScreen,
    bool? allowMuting,
    bool? allowPlaybackSpeedChanging,
    bool? useRootNavigator,
    Duration? hideControlsTimer,
    _i3.EdgeInsets? controlsSafeAreaMinimum,
    List<double>? playbackSpeeds,
    List<_i10.SystemUiOverlay>? systemOverlaysOnEnterFullScreen,
    List<_i10.DeviceOrientation>? deviceOrientationsOnEnterFullScreen,
    List<_i10.SystemUiOverlay>? systemOverlaysAfterFullScreen,
    List<_i10.DeviceOrientation>? deviceOrientationsAfterFullScreen,
    Duration? progressIndicatorDelay,
    _i3.Widget Function(
      _i3.BuildContext,
      _i3.Animation<double>,
      _i3.Animation<double>,
      _i4.ChewieControllerProvider,
    )?
    routePageBuilder,
    bool? pauseOnBackgroundTap,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #videoPlayerController: videoPlayerController,
              #optionsTranslation: optionsTranslation,
              #aspectRatio: aspectRatio,
              #autoInitialize: autoInitialize,
              #autoPlay: autoPlay,
              #draggableProgressBar: draggableProgressBar,
              #startAt: startAt,
              #looping: looping,
              #fullScreenByDefault: fullScreenByDefault,
              #cupertinoProgressColors: cupertinoProgressColors,
              #materialProgressColors: materialProgressColors,
              #materialSeekButtonFadeDuration: materialSeekButtonFadeDuration,
              #materialSeekButtonSize: materialSeekButtonSize,
              #placeholder: placeholder,
              #overlay: overlay,
              #showControlsOnInitialize: showControlsOnInitialize,
              #showOptions: showOptions,
              #optionsBuilder: optionsBuilder,
              #additionalOptions: additionalOptions,
              #showControls: showControls,
              #transformationController: transformationController,
              #zoomAndPan: zoomAndPan,
              #maxScale: maxScale,
              #subtitle: subtitle,
              #showSubtitles: showSubtitles,
              #subtitleBuilder: subtitleBuilder,
              #customControls: customControls,
              #bufferingBuilder: bufferingBuilder,
              #errorBuilder: errorBuilder,
              #allowedScreenSleep: allowedScreenSleep,
              #isLive: isLive,
              #allowFullScreen: allowFullScreen,
              #allowMuting: allowMuting,
              #allowPlaybackSpeedChanging: allowPlaybackSpeedChanging,
              #useRootNavigator: useRootNavigator,
              #hideControlsTimer: hideControlsTimer,
              #controlsSafeAreaMinimum: controlsSafeAreaMinimum,
              #playbackSpeeds: playbackSpeeds,
              #systemOverlaysOnEnterFullScreen: systemOverlaysOnEnterFullScreen,
              #deviceOrientationsOnEnterFullScreen:
                  deviceOrientationsOnEnterFullScreen,
              #systemOverlaysAfterFullScreen: systemOverlaysAfterFullScreen,
              #deviceOrientationsAfterFullScreen:
                  deviceOrientationsAfterFullScreen,
              #progressIndicatorDelay: progressIndicatorDelay,
              #routePageBuilder: routePageBuilder,
              #pauseOnBackgroundTap: pauseOnBackgroundTap,
            }),
            returnValue: _FakeChewieController_4(
              this,
              Invocation.method(#copyWith, [], {
                #videoPlayerController: videoPlayerController,
                #optionsTranslation: optionsTranslation,
                #aspectRatio: aspectRatio,
                #autoInitialize: autoInitialize,
                #autoPlay: autoPlay,
                #draggableProgressBar: draggableProgressBar,
                #startAt: startAt,
                #looping: looping,
                #fullScreenByDefault: fullScreenByDefault,
                #cupertinoProgressColors: cupertinoProgressColors,
                #materialProgressColors: materialProgressColors,
                #materialSeekButtonFadeDuration: materialSeekButtonFadeDuration,
                #materialSeekButtonSize: materialSeekButtonSize,
                #placeholder: placeholder,
                #overlay: overlay,
                #showControlsOnInitialize: showControlsOnInitialize,
                #showOptions: showOptions,
                #optionsBuilder: optionsBuilder,
                #additionalOptions: additionalOptions,
                #showControls: showControls,
                #transformationController: transformationController,
                #zoomAndPan: zoomAndPan,
                #maxScale: maxScale,
                #subtitle: subtitle,
                #showSubtitles: showSubtitles,
                #subtitleBuilder: subtitleBuilder,
                #customControls: customControls,
                #bufferingBuilder: bufferingBuilder,
                #errorBuilder: errorBuilder,
                #allowedScreenSleep: allowedScreenSleep,
                #isLive: isLive,
                #allowFullScreen: allowFullScreen,
                #allowMuting: allowMuting,
                #allowPlaybackSpeedChanging: allowPlaybackSpeedChanging,
                #useRootNavigator: useRootNavigator,
                #hideControlsTimer: hideControlsTimer,
                #controlsSafeAreaMinimum: controlsSafeAreaMinimum,
                #playbackSpeeds: playbackSpeeds,
                #systemOverlaysOnEnterFullScreen:
                    systemOverlaysOnEnterFullScreen,
                #deviceOrientationsOnEnterFullScreen:
                    deviceOrientationsOnEnterFullScreen,
                #systemOverlaysAfterFullScreen: systemOverlaysAfterFullScreen,
                #deviceOrientationsAfterFullScreen:
                    deviceOrientationsAfterFullScreen,
                #progressIndicatorDelay: progressIndicatorDelay,
                #routePageBuilder: routePageBuilder,
                #pauseOnBackgroundTap: pauseOnBackgroundTap,
              }),
            ),
          )
          as _i4.ChewieController);

  @override
  void enterFullScreen() => super.noSuchMethod(
    Invocation.method(#enterFullScreen, []),
    returnValueForMissingStub: null,
  );

  @override
  void exitFullScreen() => super.noSuchMethod(
    Invocation.method(#exitFullScreen, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleFullScreen() => super.noSuchMethod(
    Invocation.method(#toggleFullScreen, []),
    returnValueForMissingStub: null,
  );

  @override
  void togglePause() => super.noSuchMethod(
    Invocation.method(#togglePause, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setLooping(bool? looping) =>
      (super.noSuchMethod(
            Invocation.method(#setLooping, [looping]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> seekTo(Duration? moment) =>
      (super.noSuchMethod(
            Invocation.method(#seekTo, [moment]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void setSubtitle(List<_i11.Subtitle>? newSubtitle) => super.noSuchMethod(
    Invocation.method(#setSubtitle, [newSubtitle]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
